### ISSUE TITLE
Firefox 99.0 (64-bit) Ubuntu webGL error.

### ISSUE THREAD

**Issue by okunator** [genome-spy/genome-spy#98]
Encountered an error when opening up a visualization with firefox browser..

![image](https://user-images.githubusercontent.com/32158343/165100151-ad00a9c7-c586-4cef-8387-dfdb1801d152.png)

`At "viewRoot/concat0_decorator/concat0/layer0": Error: Cannot create shader program: 0(26) : error C7532: global function uintBitsToFloat requires "#version 330" or later 0(26) : error C0000: ... or #extension GL_ARB_shader_bit_encoding : enable 0(26) : error C0000: ... or #extension GL_ARB_gpu_shader5 : enable `

**Comment by tuner** [comment]
Thanks. This has to be related to ANGLE (the WebGL implementation) because I'm not using `uintBitsToFloat` anywhere in the shaders.

**Comment by tuner** [comment]
Works on Ubuntu 21.10, Firefox 99.0.1, Intel HD Graphics 4000

**Comment by tuner** [comment]
@okunator I guess this is not an issue any more?
